// [lyric, startTime, endTime, leftMargin (px)]
const RoundAndBlue = [
    ["You always gotta be ahead of the curve", 1,  34.4, 10],
    ["There are cursive prices for what you deserve", 5.2,  34.4, 30],
    ["Organizing all the screws for an empty hearted muse", 11,  34.4, 50],
    ["They say melancholy's such a fragrant place", 18, 34.4, 200],
    ["But if you wanna paint with it you gotta", 22, 34.4, 170],
    ["Pick up the pace", 25.7, 34.4, 160],
    ["Heard the corner store's got exactly what you're looking for", 28.3, 34.4, 130],
    ["Who would've thought it's dangerous", 34.4, 54, 0],
    ["  - To design a cure that makes the well-kept vagrant", 38, 54, 30],
    ["  - To entertain the thought of concerts on the pavement", 42, 54, 30],
    ["  - To slap a brand on it and make it seem less flagrant?", 46.3, 54, 30],
    ["It's round and blue", 52.2, 69.4],
    ["  Round and blue", 57, 69.4],
    ["    Round and blue", 61.4, 69.4],
    ["      Ahh...", 65.5, 69.4],
    ["Now everyday is blue", 69.4, 79.4],
    ["Round and blue", 999],
    ["Just another way to make it through", 999],
    ["Round and blue", 999],
    ["Such a purpose-driven alloy", 999],
    ["Stuck in the notion of artificial motion", 999],
    ["Has it ever crossed your mind to", 999],
    ["Give thanks and release to the earth that gave you peace?", 999],
    ["Not even a moment for silence", 999],
    ["e   5   999   2", 999],
    ["Who would've thought it's dangerous", 999],
    ["To walk in late on your arraignment", 999],
    ["For tripping up on some lab-coat casino payments", 999],
    ["Who is it here who's really hurting from an ailment?", 999],
    ["There are cursive prices for what you deserve", 999],
    ["Organizing all the screws for an empty hearted muse", 999],
    ["Every day will feel the same", 999],
    ["Blood through crystal-clear veins", 999],
    ["These translucent amber bottles that breed primetime TV models", 999],
    ["Will erode the castles floating in the air", 999],
    ["Now everyday is blue", 999],
    ["Round and blue", 999],
    ["Just another way to make it through", 999],
    ["Round and blue", 999],
    ["Everyday is round and blue", 999],
    ["Two times a day it's round and blue", 999],
    ["It doesn't come in just round and blue", 999],
    ["But in the end it's all up to you", 999],
    ["You", 999],
    ["You", 999],
]

export default RoundAndBlue;


