const Vignette = [
    ["Idyllic scenes on TV screens", 1],
    ["Makes this feel heaven-sent", 2],
    ["Whoever thought it might happen for us?", 3],
    ["", 4],
    ["A treasure map fell on my lap", 5],
    ["Could you help me mark an X on the spot?", 6],
    ["Pastiche comedy that's taken too far", 7],
    ["", 8],
    ["Frolick as the silver hours pass", 9],
    ["And Leave", 999],
    ["", 999],
    ["Listless and restless", 999],
    ["I saunter down", 999],
    ["The neon streets", 999],
    ["Shopping for whatever sticks", 999],
    ["Makes chemicals rush", 999],
    ["", 999],
    ["Didn't I promise to play nice with affection", 999],
    ["Not dart for directions with porcelain trees?", 999],
    ["", 999],
    ["Love", 999],
    ["Is ", 999],
    ["Not ", 999],
    ["A ", 999],
    ["Game", 999],
    ["", 999],
    ["Switching out the pieces on the board", 999],
    ["Will never cancel out the pain that you afford", 999],
    ["", 999],
    ["Stormy ", 999],
    ["Weather", 999],
    ["Came", 999],
    ["(And cleared too soon)", 999],
    ["", 999],
    ["Limerance and blindfolds", 999],
    ["On tightropes", 999],
    ["Can leave you too soon", 999],
    ["", 999],
    ["I'm trying", 999],
    ["I'm trying", 999],
    ["I'm trying", 999],
    ["", 999],
    ["Not to throw it all away", 999],
    ["And fly free", 999],
    ["", 999],
    ["It could be fright ", 999],
    ["Or appetite", 999],
    ["Maybe all the things that keep me up at night", 999],
    ["They're subliminally pointing and laughing at me", 999],
    ["It seems that I'm just trying to stop", 999],
    ["", 999],
    ["All the floorboard gazing", 999],
    ["All the morning dazing", 999],
    ["Polyester freezing", 999],
    ["Scientific teasing", 999],
    ["Parking far to talk", 999],
    ["A million mile walk", 999],
    ["While tracing all our paths", 999],
    ["With smile-colored chalk", 999],
    ["", 999],
    ["How could I build this alphabet", 999],
    ["A castle made of sand the shore might soon forget ", 999],
    ["Spending life tumbling after the next", 999],
    ["Vignette?", 999],
    ["", 999],
    ["Vignette", 999],
    ["Vignette", 999],
    ["Vignette", 999],
    ["Vignette", 999],
    ["Vignette", 999],
    ["Vignette", 999],
    ["Vignette", 999],
]

export default Vignette;
